### ISSUE TITLE
Project Activity

### ISSUE THREAD

**Issue by snowy-jaguar** [foamkeen/nut-docker#1]
Hi, Is this project still being developed/updated? I was looking for a docker version of NUT that I could put in a docker compose file inside of Portainer and your project here looks really good however I'm not the best at converting DockerFile to docker-compose as I'm rather new to docker.

**Comment by snowy-jaguar** [comment]
Also am I able to pass multiple `--device` into the command?

**Comment by foamkeen** [comment]
Hi, not it is not being actively developed.

`--device` is a `docker run` command line option and as [Docker's documentation](https://docs.docker.com/engine/reference/commandline/run/#device) suggests, you can pass multiple devices.
